### ISSUE TITLE
Resize checkbox

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUtils/material.avalonia#50]
Set checkbox bigger.
![image](https://user-images.githubusercontent.com/33497292/96253414-35741380-0fbc-11eb-8c38-73f9d2151b6a.png)
https://material.io/components/selection-controls#usage

**Comment by SKProCH** [comment]
This can be done through `CheckBoxAssist.CheckBoxSize="24"`. Added sample to demo in 64b5a2600f09a64ec9c9b3e084be6ef63e717e93
