### ISSUE TITLE
Freeze ripple effect till focus doesn't lost

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUtils/material.avalonia#51]
After click on check element (like chekbox, radio button...) ripple effect should freeze till lost focus.
![image](https://user-images.githubusercontent.com/33497292/96253667-b3d0b580-0fbc-11eb-8b70-7c7b93164b6a.png)
Check it [here](https://material.io/components/tabs#interactive-demo)

**Comment by SKProCH** [comment]
Fixed in 2628bc74dd8e346208280a6550c76a912398db42 6712d39ac78ea24e699d9a193f5923280684c0d9 ba8e2c9020e6037cdd760f72b46abea61f4e2cda.
