### ISSUE TITLE
NumericUpDown arrows

### ISSUE THREAD

**Issue by AlienJust** [AvaloniaUtils/material.avalonia#59]
It is very hard to click (by mouse) on arrows of NumericUpDown control. Click area is very small and there is no visual feedback when mouse cursor is over the area.
![out2](https://user-images.githubusercontent.com/739189/97260968-b0042500-183f-11eb-887d-1a2a5c2da1e5.gif)

**Comment by CreateLab** [comment]
![image](https://user-images.githubusercontent.com/33497292/97293466-c0c39380-185d-11eb-8ef7-2c5ce0f325c8.png)
