### ISSUE TITLE
Min Scrollbar

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUtils/material.avalonia#62]
`<ScrollBar Styles="Mini"/>`

<img width="57" alt="Снимок" src="https://user-images.githubusercontent.com/33497292/99222614-fc65d380-27f3-11eb-8b1a-d2c1836db4be.PNG">

**Comment by appleneko2001** [comment]
How about this one? I implemented this ScrollBar style (vertical only)

For use this one just need add "Mini" to classes ScrollBar

![](https://user-images.githubusercontent.com/38249047/103745717-51c79f80-5043-11eb-82b5-16db890464b6.png)

**Comment by SKProCH** [comment]
@appleneko2001 can you create a pull request to us back to the repository? You have done a lot of work
