### ISSUE TITLE
Help required on menu and menu items

### ISSUE THREAD

**Issue by Junaid-Amjad** [AvaloniaUtils/material.avalonia#75]
Hi, i am recently moved from winform to wpf and i am still exploring wpf structure. I am working on the menu and face issue with the display as indicated in below gif. I tried to change the foreground color but it's display remain the same. hope you can help me sorting out this issue.  
![AvaloniaMenu](https://user-images.githubusercontent.com/75033105/106004132-b58a3900-60d4-11eb-9436-095c568f0f95.gif)

**Comment by Junaid-Amjad** [comment]
Just a quick note, i added the `<FluentTheme Mode="Light"/>` in App.xaml and it worked, but style of some controls (Tab) are not applied. Is there any solution related to this mechanism. 
![AvaloniaMenu2](https://user-images.githubusercontent.com/75033105/106018295-2e908d00-60e3-11eb-85a4-36d9c1d5cd72.gif)

**Comment by appleneko2001** [comment]
Our library doenst use Avalonia Fluent theme definitions so `<FluentTheme Mode="Light"/>` it will not affect to most controls, but some controls could be affected with this.

And another thing is why Popup not using Material styles, using default instead. What version of Material.Avalonia you are using now?

**Comment by Junaid-Amjad** [comment]
@appleneko2001 i am using Material.Avalonia 1.0.1 and use the styles from the Material.Styles for some controls as shown in below
![AvaloniaMenu3](https://user-images.githubusercontent.com/75033105/106121867-da84b780-6179-11eb-9644-c425904d1bf4.gif)

**Comment by appleneko2001** [comment]
In your case, you want to style a few controls and apply palette to window right?

For change color palette of styled controls you need use this line to Resources. For custom colors: https://material.io/design/color/the-color-system.html#tools-for-picking-colors

`<themes:BundledTheme BaseTheme="Light" PrimaryColor="Teal" SecondaryColor="Amber"/>`

![изображение](https://user-images.githubusercontent.com/38249047/106123806-bc30b300-619d-11eb-85ee-e2ead363208c.png)

**Comment by Junaid-Amjad** [comment]
> In your case, you want to style a few controls and apply palette to window right?

Not exactly, At first, i used all the controls of material.avalonia and add the style reference as you described above. Issue came when i used `Menu` Tag as i shared in my first message. I shared the app.xaml file for reference
![1-28-2021 4-14-02 PM](https://user-images.githubusercontent.com/75033105/106131021-f5f4c000-6183-11eb-83cd-5bc180cd2c92.png)

**Comment by Junaid-Amjad** [comment]
I believe `Material.Styles/Menu.xaml` is not operational

**Comment by appleneko2001** [comment]
MenuItem are affected by opacity, can you add `Opacity="1"` to main MenuItem to make it visible? 
later we'll solve this bug in next update

**Comment by Junaid-Amjad** [comment]
`MenuItem` works fine when it is used without `Menu` Tag. In below image, `MenuItem` style work perfectly with `Material.Styles.Card`. When `MenuItem` is use with `Menu` Tag then it's display is corrupt even  if we add `Opacity = "1"`. 
![AvaloniaMenu4](https://user-images.githubusercontent.com/75033105/106148768-475c7980-619b-11eb-9ad2-8c55cbb5caca.gif)

**Comment by appleneko2001** [comment]
I just push fixes to dev branch, can you download the dev branch and compile it yourself?

**Comment by Junaid-Amjad** [comment]
After compile, result seems pretty clear. So, this feature will be available in the next update? 
![AvaloniaMenu5](https://user-images.githubusercontent.com/75033105/106161334-a83e7e80-61a8-11eb-9ef1-f49bce736d6c.gif)

**Comment by appleneko2001** [comment]
yea it will be appear on next update and will improved on future update to solve this issue completely

**Comment by appleneko2001** [comment]
This issue will closed. Any future updates about this problem will appeared in new issue #78
