### ISSUE TITLE
TabControl properties

### ISSUE THREAD

**Issue by Junaid-Amjad** [AvaloniaUtils/material.avalonia#76]
Hi, this is more like a question about TabControl. Is there any property included in TabControl where button can be added at the end of the control as indicated in the figure. 
![1-29-2021 8-28-15 PM](https://user-images.githubusercontent.com/75033105/106294208-b3f57800-6270-11eb-8a67-53b0d1306579.png)
I have checked the `TabControl.xaml` but i didnot find any styling for this feature. However i used scrollviewer to resume my work as indicated below.
![AvaloniaTab](https://user-images.githubusercontent.com/75033105/106294435-fd45c780-6270-11eb-9956-e2c7a198ec0c.gif)

Is there any article exist where i can achieve above functionality in Avalonia XAML?

**Comment by appleneko2001** [comment]
I still working on TabControl improvements and customized scroller, solution will be appeared later

**Comment by appleneko2001** [comment]
uh my oopsie not bug label, its more like a enhancement

**Comment by appleneko2001** [comment]
I created a TabControl that could scrolling in dev branch, for more information about this: https://github.com/AvaloniaUtils/material.avalonia/commit/e9db3b62ef73c7e91edab93a62c8f6e680487793#commitcomment-46561963

Can you compile dev branch again for new feature?

**Comment by Junaid-Amjad** [comment]
Yes i compiled it and seems like my problem can be resolved from this feature. Now i am waiting for this feature to be added in the master branch. It tried to use the `TabControl` style in my project but it seems like there are many classes/functions/files which are not included in the `master` branch.

**Comment by appleneko2001** [comment]
This issue will be closed. Any news about this problem will appear in issue #79
