### ISSUE TITLE
TextBox.Outline's floating watermark background is always MaterialDesignPaper

### ISSUE THREAD

**Issue by js6pak** [AvaloniaUtils/material.avalonia#89]
For example try adding a TextBox into a Card
![2021-05-01_22-00](https://user-images.githubusercontent.com/35262707/116793720-e43ef380-aab7-11eb-961c-8ecb826fbd86.png)

This would be a working workaround, but seems like https://github.com/AvaloniaUI/Avalonia/issues/2098 breaks it
```xml
<Style Selector="TextBox.Outline /template/ Border#watermarkRoot">
	<Setter Property="Background" Value="{DynamicResource MaterialDesignCardBackground}" />
</Style>
```

**Comment by appleneko2001** [comment]
I just pushed an [temporarily fix](https://github.com/AvaloniaUtils/material.avalonia/commit/0ac9caccb41ad0798ed87ab25acefde886a18ca7) for background color 
You can build `dev` branch yourself if you need this fix as fast as possible.

**Comment by appleneko2001** [comment]
Ok I commited an feature that clipping the outline textfield even in transparent or colorful background. You can forgot the issue of background color should be same

![](https://user-images.githubusercontent.com/38249047/116808151-380e1300-ab72-11eb-82ed-fb02a4672f49.gif)
